DEEPSORT:
  REID_CKPT: "deep_sort_pytorch/deep_sort/deep/checkpoint/ckpt.t7"
  # REID_CKPT: "E:/Bristol Project/YOLOv5+DeepSort2.0/yolo_tracking-3.0/deep_sort_pytorch/deep_sort/deep/checkpoint/visem0.1_v5n.t7"
  MAX_DIST: 0.2
  MIN_CONFIDENCE: 0.3
  NMS_MAX_OVERLAP: 0.5
  MAX_IOU_DISTANCE: 0.7
  MAX_AGE: 70
  N_INIT: 3
  NN_BUDGET: 100
  
